#!/usr/bin/env bash
# PostgreSQL + Redis for a development box, in containers.
#
# Why containers: a development machine is usually shared with other projects.
# Installing PostgreSQL and Redis as system services changes the machine for
# everyone on it; two containers can be started, stopped and thrown away
# without touching anything else.
#
# Deliberate choices, all of them about not disturbing the host:
#   * container and volume names are prefixed jtipam-dev- so they cannot
#     collide with another project's containers
#   * ports are bound to 127.0.0.1 only, and on non-default numbers, so we do
#     not take 5432/6379 away from anything that may want them later
#   * no compose plugin required -- plain docker run, nothing to install
#
# This is for development only. Production installs use the system PostgreSQL
# (see scripts/jt-ipam.sh).
#
# Usage: dev-services.sh {up|down|status|psql|env}

set -euo pipefail

PG_CONTAINER=jtipam-dev-postgres
REDIS_CONTAINER=jtipam-dev-redis
PG_VOLUME=jtipam-dev-pgdata
PG_IMAGE=pgvector/pgvector:pg16          # pgvector 官方映像；語意搜尋需要 vector 擴充
REDIS_IMAGE=redis:7-alpine
PG_PORT=${JTIPAM_DEV_PG_PORT:-55432}
REDIS_PORT=${JTIPAM_DEV_REDIS_PORT:-56379}

# Durability off, on purpose. conftest TRUNCATEs 102 tables before every test and
# each TRUNCATE fsyncs, which is what the backend suite actually spends its time
# on: measured on this box it ran at 6.7 tests/min with fsync on and 105/min with
# it off -- 3 hours versus 15 minutes for the same 1,549 tests. These databases
# are disposable (recreated by alembic + fixtures), so a crash costs nothing that
# is not already reproducible. Never do this to a database anyone cares about.
PG_DURABILITY_OFF=(-c fsync=off -c synchronous_commit=off -c full_page_writes=off)
PG_USER=jt_ipam
PG_MAIN_DB=jt_ipam
ENV_FILE=${JTIPAM_DEV_ENV:-/opt/jt-ipam/.dev.env}

die() { echo "error: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

secret() { head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32; }

up() {
    have docker || die "docker is not available"

    # Credentials live in one gitignored file and are generated once. Reusing
    # them on restart matters: regenerating would leave the existing volume
    # unreadable, which looks exactly like data loss.
    if [[ -f "$ENV_FILE" ]]; then
        # shellcheck disable=SC1090
        set -a; source "$ENV_FILE"; set +a
    else
        POSTGRES_PASSWORD="$(secret)"
        REDIS_PASSWORD="$(secret)"
        # 名稱必須與 app/core/config.py 的欄位一致，長度 >= 32（見 _MIN_SECRET_BYTES）
        SECRET_KEY="$(secret)$(secret)"
        ENCRYPTION_KEY="$(secret)$(secret)"
        AUDIT_CHAIN_GENESIS="$(secret)$(secret)"
        umask 077
        cat > "$ENV_FILE" <<EOF
# jt-ipam development environment (generated by deploy/dev-services/dev-services.sh).
# Gitignored on purpose. Not production credentials; not for anything reachable
# from outside this machine.
APP_ENV=development
APP_DEBUG=false
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=$PG_PORT
POSTGRES_USER=$PG_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$PG_MAIN_DB
REDIS_HOST=127.0.0.1
REDIS_PORT=$REDIS_PORT
REDIS_PASSWORD=$REDIS_PASSWORD
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
AUDIT_CHAIN_GENESIS=$AUDIT_CHAIN_GENESIS
BACKEND_TLS_MODE=nginx
BACKEND_BIND_HOST=127.0.0.1
# SSL 是硬性需求，config.py 的 _tls_guards 在**任何環境**都要求這兩個是 https://；
# 少了它們連 alembic 都起不來（Settings 驗證就先失敗）。開發時只是字面值，
# 前端仍走 http://127.0.0.1:5173。
APP_PUBLIC_URL=https://localhost:5173
API_PUBLIC_URL=https://localhost:8443
CORS_ORIGINS=http://127.0.0.1:5173,http://127.0.0.1:5199
JTIPAM_TEST_DATABASE_URL=postgresql+asyncpg://$PG_USER:$POSTGRES_PASSWORD@127.0.0.1:$PG_PORT/jt_ipam_test
EOF
        echo "wrote $ENV_FILE"
    fi

    if ! docker ps -a --format '{{.Names}}' | grep -qx "$PG_CONTAINER"; then
        docker volume create "$PG_VOLUME" >/dev/null
        docker run -d --name "$PG_CONTAINER" --restart unless-stopped \
            -e POSTGRES_USER="$PG_USER" \
            -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            -e POSTGRES_DB="$PG_MAIN_DB" \
            -p "127.0.0.1:$PG_PORT:5432" \
            -v "$PG_VOLUME:/var/lib/postgresql/data" \
            "$PG_IMAGE" "${PG_DURABILITY_OFF[@]}" >/dev/null
        echo "started $PG_CONTAINER on 127.0.0.1:$PG_PORT"
    else
        docker start "$PG_CONTAINER" >/dev/null && echo "$PG_CONTAINER running"
    fi

    # 密碼漂移：容器的 requirepass 是**啟動當下**寫死的，env 檔事後重產就對不上，
    # 症狀是後端 WRONGPASS 而容器看起來一切正常。redis 這裡只當快取，重建沒有代價。
    if docker ps -a --format '{{.Names}}' | grep -qx "$REDIS_CONTAINER"; then
        # `println` 會在最後多一個空行，用 tail -1 抓到的是空字串 —— 那會讓每一次
        # up 都判定成漂移。用 join 取整條命令列再比對子字串。
        running_cmd="$(docker inspect "$REDIS_CONTAINER" --format '{{join .Config.Cmd " "}}')"
        if [[ "$running_cmd" != *"--requirepass $REDIS_PASSWORD"* ]]; then
            echo "$REDIS_CONTAINER password drifted from $ENV_FILE -- recreating"
            docker rm -f "$REDIS_CONTAINER" >/dev/null
        fi
    fi
    if ! docker ps -a --format '{{.Names}}' | grep -qx "$REDIS_CONTAINER"; then
        docker run -d --name "$REDIS_CONTAINER" --restart unless-stopped \
            -p "127.0.0.1:$REDIS_PORT:6379" \
            "$REDIS_IMAGE" redis-server --requirepass "$REDIS_PASSWORD" >/dev/null
        echo "started $REDIS_CONTAINER on 127.0.0.1:$REDIS_PORT"
    else
        docker start "$REDIS_CONTAINER" >/dev/null && echo "$REDIS_CONTAINER running"
    fi

    echo -n "waiting for postgres"
    for _ in $(seq 1 40); do
        if docker exec "$PG_CONTAINER" pg_isready -U "$PG_USER" -q 2>/dev/null; then
            echo " ok"; break
        fi
        echo -n "."; sleep 1
    done

    # 同樣的漂移在 postgres 上更難認：POSTGRES_PASSWORD 只在**初始化 volume 那一次**
    # 生效，之後改 env 檔完全不會反映到資料庫，而容器內走 unix socket / 127.0.0.1 是
    # trust，怎麼測都是通的 —— 只有從主機經 TCP 連才會 InvalidPasswordError。
    # 每次 up 都把角色密碼設成 env 檔的值，就不會有第二種真相。
    docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d postgres -q \
        -c "ALTER ROLE $PG_USER PASSWORD '$POSTGRES_PASSWORD'"

    # The three databases the workflow expects, plus the extensions. Creating
    # them here rather than by hand keeps a fresh box one command away from
    # being able to run the test suite.
    for db in "$PG_MAIN_DB" jt_ipam_test jt_ipam_e2e; do
        docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d postgres -tAc \
            "SELECT 1 FROM pg_database WHERE datname='$db'" | grep -q 1 || \
            docker exec "$PG_CONTAINER" createdb -U "$PG_USER" "$db"
        docker exec "$PG_CONTAINER" psql -U "$PG_USER" -d "$db" -q -c \
            "CREATE EXTENSION IF NOT EXISTS vector; CREATE EXTENSION IF NOT EXISTS pg_trgm;"
        echo "database $db ready (vector, pg_trgm)"
    done
    echo
    echo "environment: $ENV_FILE   (set -a; source $ENV_FILE; set +a)"
}

down() {
    docker stop "$PG_CONTAINER" "$REDIS_CONTAINER" 2>/dev/null || true
    echo "stopped (data kept in volume $PG_VOLUME; 'docker volume rm $PG_VOLUME' to discard)"
}

status() {
    docker ps -a --filter "name=jtipam-dev-" \
        --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
}

psql_() {
    # shellcheck disable=SC1090
    set -a; source "$ENV_FILE"; set +a
    docker exec -it "$PG_CONTAINER" psql -U "$PG_USER" -d "${1:-$PG_MAIN_DB}"
}

case "${1:-}" in
    up)     up ;;
    down)   down ;;
    status) status ;;
    psql)   shift; psql_ "${1:-}" ;;
    env)    echo "$ENV_FILE" ;;
    *)      echo "usage: $0 {up|down|status|psql [db]|env}"; exit 2 ;;
esac
